### ISSUE TITLE
Error occurs when tpcds-gen was submitted.

### ISSUE THREAD

**Issue by daegyu94** [t3rmin4t0r/tpcds-gen#2]
Hi, I'm originally going to use the hive-testbench benchmark, but I have a problem with tpcds-gen, so I leave a question here.

'make' result shows success message including mvn compile.
However, When I used 'yarn jar ~~ ' to submit job to my cluster, I had some error message. I tried to solve this problem but I can't find any solution now..

This is the error message... 

> TaskAttempt 3 failed, info=[Error: Error while running task ( failure ) : attempt_1592017640309_0001_1_00_000003_3:java.io.IOException: Cannot run program "" (in directory "dsdgen/tools"): error=2, No such file or directory
>         at java.lang.ProcessBuilder.start(ProcessBuilder.java:1042)
>         at java.lang.Runtime.exec(Runtime.java:620)
>         at org.notmysock.tpcds.GenTable$DSDGen.map(GenTable.java:190)
>         at org.notmysock.tpcds.GenTable$DSDGen.map(GenTable.java:163)
>         at org.apache.hadoop.mapreduce.Mapper.run(Mapper.java:146)
>         at org.apache.tez.mapreduce.processor.map.MapProcessor.runNewMapper(MapProcessor.java:248)
>         at org.apache.tez.mapreduce.processor.map.MapProcessor.run(MapProcessor.java:135)
>         at org.apache.tez.runtime.LogicalIOProcessorRuntimeTask.run(LogicalIOProcessorRuntimeTask.java:374)
>         at org.apache.tez.runtime.task.TaskRunner2Callable$1.run(TaskRunner2Callable.java:73)
>         at org.apache.tez.runtime.task.TaskRunner2Callable$1.run(TaskRunner2Callable.java:61)
>         at java.security.AccessController.doPrivileged(Native Method)
>         at javax.security.auth.Subject.doAs(Subject.java:422)
>         at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1893)
>         at org.apache.tez.runtime.task.TaskRunner2Callable.callInternal(TaskRunner2Callable.java:61)
>         at org.apache.tez.runtime.task.TaskRunner2Callable.callInternal(TaskRunner2Callable.java:37)
>         at org.apache.tez.common.CallableWithNdc.call(CallableWithNdc.java:36)
>         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
>         at java.lang.Thread.run(Thread.java:744)
> Caused by: java.io.IOException: error=2, No such file or directory
>         at java.lang.UNIXProcess.forkAndExec(Native Method)
>         at java.lang.UNIXProcess.<init>(UNIXProcess.java:187)
>         at java.lang.ProcessImpl.start(ProcessImpl.java:134)
>         at java.lang.ProcessBuilder.start(ProcessBuilder.java:1023)
>         ... 19 more

|
Do you know why I get this error message?

**Comment by daegyu94** [comment]
Sorry, I modified Mapreduce linerecordreader source code.
That is the reason why this happens..
